name: AndroidBuild

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
   lint:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.5

       - name: Setup Java JDK
         uses: actions/setup-java@v4.2.1
         with:
           java-version: '17'
           distribution: 'adopt'

       - name: Add Gradle
         run: chmod +x ./gradlew

       - name: Build with Gradle
         run: ./gradlew build

       - name: Run Lint
         run: ./gradlew lintDebug

       - name: Upload html test report
         uses: actions/upload-artifact@v4.3.3
         with:
           name: lint.html
           path: app/build/reports/lint-results-debug.html

   unit-test:
     needs: [lint]
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
         uses: actions/checkout@v4.1.5

       - name: Setup Java JDK
         uses: actions/setup-java@v4.2.1
         with:
           java-version: '17'
           distribution: 'adopt'

       - name: Add Gradle
         run: chmod +x ./gradlew

       - name: Build with Gradle
         run: ./gradlew build

       - name: Run tests
         run: ./gradlew test

       - name: Upload test report
         uses: actions/upload-artifact@v4.3.3
         with:
           name: unit_test_report
           path: app/build/reports/tests/testDebugUnitTest/

   ui-test:
    needs: [unit-test]
    runs-on: ubuntu-latest
    steps:

      - name: Checkout the code
        uses: actions/checkout@v4.1.5

      - name: Setup Java JDK
        uses: actions/setup-java@v4.2.1
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Add Gradle
        run: chmod +x ./gradlew



   generate-apk:
    needs: [ui-test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.0

      - name: Setup Java JDK
        uses: actions/setup-java@v3.13.0
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Add Gradle
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.3
        with:
          name: Musix.apk
          path: app/build/outputs/apk/debug/app-debug.apk
